//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProjectCsharp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public int id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Identification { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public string Password { get; set; }
        public string FullName { get; set; }
        public Nullable<int> Subject_id { get; set; }
    
        public virtual Subject Subject { get; set; }
    }
}
